# Generated by Django 5.0.3 on 2024-03-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bullets',
            options={'ordering': ['-dateCreation']},
        ),
        migrations.AddField(
            model_name='bullets',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=128),
        ),
        migrations.AddIndex(
            model_name='bullets',
            index=models.Index(fields=['-dateCreation'], name='bbapp_bulle_dateCre_19fe5a_idx'),
        ),
    ]
