# Generated by Django 5.0.3 on 2024-03-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0002_alter_bullets_options_bullets_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullets',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
    ]
