# Generated by Django 5.0.3 on 2024-03-10 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0005_category_bullets_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullets',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bbapp.category'),
        ),
    ]
