# Generated by Django 5.0.3 on 2024-03-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0013_alter_bullets_content_alter_comment_commentauthor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
